import { test, expect } from "@playwright/test";

/**
 * "Page loads" smoke for the admin surface: every static admin page should render
 * the authenticated admin shell without bouncing to login or crashing. One test
 * per route so the E2E_CHECKLIST can be ticked per page. Deeper per-flow journeys
 * live in their own specs (e.g. cube-instances.spec.ts).
 *
 * Param/detail routes (`:id`) are covered by dedicated specs with seeded data.
 */
const ROUTES: Array<[id: string, path: string]> = [
  ["ADM-HOME-01", "/admin-dashboard"],
  ["ADM-HOME-02", "/admin-dashboard/analytics"],
  ["ADM-HOME-03", "/admin-dashboard/noc"],
  ["ADM-COMP-01", "/admin-dashboard/projects"],
  ["ADM-COMP-02", "/admin-dashboard/projects/create"],
  ["ADM-COMP-06", "/admin-dashboard/create-instance"],
  ["ADM-COMP-07", "/admin-dashboard/templates"],
  ["ADM-COMP-08", "/admin-dashboard/infrastructure/key-pairs"],
  ["ADM-COMP-10", "/admin-dashboard/object-storage"],
  ["ADM-COMP-13", "/admin-dashboard/databases"],
  ["ADM-COMP-16", "/admin-dashboard/cloud-accounts"],
  ["ADM-COMP-19", "/admin-dashboard/monitoring"],
  ["ADM-COMP-23", "/admin-dashboard/provider-discovery"],
  ["ADM-NET-01", "/admin-dashboard/infrastructure/vpcs"],
  ["ADM-NET-02", "/admin-dashboard/infrastructure/subnets"],
  ["ADM-NET-03", "/admin-dashboard/infrastructure/security-groups"],
  ["ADM-NET-05", "/admin-dashboard/infrastructure/load-balancers"],
  ["ADM-NET-06", "/admin-dashboard/infrastructure/dns"],
  ["ADM-NET-07", "/admin-dashboard/infrastructure/network-acls"],
  ["ADM-NET-09", "/admin-dashboard/infrastructure/vpc-peering"],
  ["ADM-NET-10", "/admin-dashboard/infrastructure/network-interfaces"],
  ["ADM-NET-12", "/admin-dashboard/infrastructure/route-tables"],
  ["ADM-NET-13", "/admin-dashboard/infrastructure/nat-gateways"],
  ["ADM-NET-14", "/admin-dashboard/infrastructure/elastic-ips"],
  ["ADM-NET-15", "/admin-dashboard/infrastructure/snapshots"],
  ["ADM-NET-16", "/admin-dashboard/infrastructure/images"],
  ["ADM-NET-17", "/admin-dashboard/infrastructure/autoscaling"],
  ["ADM-NET-18", "/admin-dashboard/shield/domains"],
  ["ADM-NET-20", "/admin-dashboard/shield/firewall"],
  ["ADM-NET-21", "/admin-dashboard/shield/attack-map"],
  ["ADM-NET-22", "/admin-dashboard/shield/attacks"],
  ["ADM-NET-23", "/admin-dashboard/shield/analytics"],
  ["ADM-NET-24", "/admin-dashboard/shield/ssl"],
  ["ADM-RES-01", "/admin-dashboard/integrations/orbit/vms"],
  ["ADM-RES-04", "/admin-dashboard/migrations"],
  ["ADM-RES-06", "/admin-dashboard/batch-migrations"],
  ["ADM-RES-09", "/admin-dashboard/orbit/calculator"],
  ["ADM-RES-10", "/admin-dashboard/move-my-email"],
  ["ADM-RES-19", "/admin-dashboard/protection"],
  ["ADM-RES-20", "/admin-dashboard/database-replication"],
  ["ADM-RES-24", "/admin-dashboard/dr-drills"],
  ["ADM-RES-25", "/admin-dashboard/serverless-dr"],
  ["ADM-RES-27", "/admin-dashboard/ransomware"],
  ["ADM-RES-28", "/admin-dashboard/hypervisor"],
  ["ADM-RES-29", "/admin-dashboard/destinations"],
  ["ADM-RES-31", "/admin-dashboard/agent"],
  ["ADM-DEPLOY-01", "/admin-dashboard/flow-dashboard"],
  ["ADM-CUST-01", "/admin-dashboard/partners"],
  ["ADM-CUST-04", "/admin-dashboard/clients"],
  ["ADM-CUST-07", "/admin-dashboard/leads"],
  ["ADM-CUST-10", "/admin-dashboard/regions"],
  ["ADM-CUST-14", "/admin-dashboard/region-approvals"],
  ["ADM-CUST-18", "/admin-dashboard/onboarding-review"],
  ["ADM-CUST-19", "/admin-dashboard/onboarding-settings"],
  ["ADM-BILL-01", "/admin-dashboard/invoices"],
  ["ADM-BILL-03", "/admin-dashboard/create-invoice"],
  ["ADM-BILL-04", "/admin-dashboard/pricing"],
  ["ADM-BILL-09", "/admin-dashboard/pricing-calculator"],
  ["ADM-BILL-10", "/admin-dashboard/products"],
  ["ADM-BILL-11", "/admin-dashboard/product-families"],
  ["ADM-BILL-13", "/admin-dashboard/inventory"],
  ["ADM-BILL-17", "/admin-dashboard/subscription-plans"],
  ["ADM-BILL-18", "/admin-dashboard/tax-configuration"],
  ["ADM-BILL-19", "/admin-dashboard/exchange-rates"],
  ["ADM-BILL-20", "/admin-dashboard/accounting"],
  ["ADM-BILL-21", "/admin-dashboard/wallet"],
  ["ADM-BILL-22", "/admin-dashboard/settlements"],
  ["ADM-BILL-23", "/admin-dashboard/payouts"],
  ["ADM-BILL-24", "/admin-dashboard/payment-splits"],
  ["ADM-BILL-25", "/admin-dashboard/payment"],
  ["ADM-BILL-27", "/admin-dashboard/poc-trials"],
  ["ADM-DEV-01", "/admin-dashboard/bridge-clients"],
  ["ADM-DEV-02", "/admin-dashboard/purchased-modules"],
  ["ADM-OPS-01", "/admin-dashboard/ops/failed-jobs"],
  ["ADM-OPS-02", "/admin-dashboard/tickets"],
  ["ADM-ACCT-01", "/admin-dashboard/account"],
  ["ADM-ACCT-02", "/admin-dashboard/security/2fa"],
  ["ADM-ACCT-03", "/admin-dashboard/security/2fa-policy"],
  ["ADM-DOCS-01", "/admin-dashboard/docs"],
  // --- create forms, sub-tabs & standalone pages (quick-win additions) ---
  ["ADM-HOME-06", "/admin-dashboard/noc/docs/grafana"],
  ["ADM-COMP-09", "/admin-dashboard/key-pairs/create"],
  ["ADM-COMP-11", "/admin-dashboard/object-storage/create"],
  ["ADM-COMP-14", "/admin-dashboard/databases/create"],
  ["ADM-COMP-17", "/admin-dashboard/cloud-accounts/create"],
  ["ADM-COMP-20", "/admin-dashboard/monitoring/pricing"],
  ["ADM-COMP-21", "/admin-dashboard/monitoring/subscriptions"],
  ["ADM-NET-04", "/admin-dashboard/infrastructure/security-group-rules"],
  ["ADM-NET-08", "/admin-dashboard/infrastructure/network-acl-rules"],
  ["ADM-NET-11", "/admin-dashboard/infrastructure/internet-gateways"],
  ["ADM-RES-02", "/admin-dashboard/integrations/orbit/vms/new"],
  ["ADM-RES-05", "/admin-dashboard/migrations/new"],
  ["ADM-RES-07", "/admin-dashboard/batch-migrations/new"],
  ["ADM-RES-11", "/admin-dashboard/integrations/orbit/buckets/endpoints"],
  ["ADM-RES-12", "/admin-dashboard/integrations/orbit/buckets/migrations"],
  ["ADM-RES-13", "/admin-dashboard/integrations/orbit/buckets/migrations/new"],
  ["ADM-RES-15", "/admin-dashboard/integrations/orbit/buckets/replications"],
  ["ADM-RES-16", "/admin-dashboard/integrations/orbit/buckets/replications/new"],
  ["ADM-RES-18", "/admin-dashboard/integrations/orbit/buckets/client-access"],
  ["ADM-RES-26", "/admin-dashboard/serverless-dr/new"],
  ["ADM-RES-30", "/admin-dashboard/destinations/new"],
  ["ADM-RES-32", "/admin-dashboard/integrations/orbit/two-factor"],
  ["ADM-RES-33", "/admin-dashboard/integrations/orbit/ip-allowlist"],
  ["ADM-RES-34", "/admin-dashboard/integrations/orbit/ssh-host-keys"],
  ["ADM-RES-35", "/admin-dashboard/integrations/orbit/api-keys/rotate"],
  ["ADM-RES-36", "/admin-dashboard/integrations/orbit/audit-log"],
  ["ADM-RES-37", "/admin-dashboard/integrations/orbit/notifications"],
  ["ADM-RES-38", "/admin-dashboard/integrations/orbit/webhook-dlq"],
  ["ADM-RES-39", "/admin-dashboard/orbit/fast-track"],
  ["ADM-RES-40", "/admin-dashboard/orbit/direct-provision"],
  ["ADM-DEPLOY-02", "/admin-dashboard/flow-dashboard?tab=servers"],
  ["ADM-DEPLOY-03", "/admin-dashboard/flow-dashboard?tab=sites"],
  ["ADM-DEPLOY-04", "/admin-dashboard/flow-dashboard?tab=git-providers"],
  ["ADM-DEPLOY-05", "/admin-dashboard/flow-dashboard?tab=databases"],
  ["ADM-CUST-02", "/admin-dashboard/partners/create"],
  ["ADM-CUST-05", "/admin-dashboard/clients/create"],
  ["ADM-CUST-08", "/admin-dashboard/leads/create"],
  ["ADM-CUST-11", "/admin-dashboard/regions/create"],
  ["ADM-CUST-15", "/admin-dashboard/region-approvals/create"],
  ["ADM-BILL-05", "/admin-dashboard/pricing/edit"],
  ["ADM-BILL-06", "/admin-dashboard/pricing/unit-costs"],
  ["ADM-BILL-07", "/admin-dashboard/pricing/fx-rates"],
  ["ADM-BILL-08", "/admin-dashboard/pricing/localizations"],
  ["ADM-BILL-12", "/admin-dashboard/catalog/add"],
  ["ADM-BILL-14", "/admin-dashboard/inventory/image-requests"],
  ["ADM-BILL-15", "/admin-dashboard/inventory/load-balancers"],
  ["ADM-BILL-16", "/admin-dashboard/inventory/dns-zones"],
  ["ADM-BILL-28", "/admin-dashboard/integration-partner-payouts"],
  ["ADM-BILL-29", "/admin-dashboard/integration-partner-payouts/ledger"],
  ["ADM-BILL-30", "/admin-dashboard/partners/monitoring"],
  ["ADM-BILL-31", "/admin-dashboard/partners/report-subscriptions"],
  ["ADM-OPS-04", "/admin-dashboard/_dev/primitives"],
  ["ADM-DOCS-02", "/admin-dashboard/docs/edit"],
];

test.describe("admin · page loads", () => {
  for (const [id, path] of ROUTES) {
    test(`${id} loads (${path})`, async ({ page }) => {
      await page.goto(path, { waitUntil: "domcontentloaded" });
      // Session valid (not bounced) and the authenticated admin shell rendered.
      await expect(page).not.toHaveURL(/\/(sign-in|verify-mail)/);
      await expect(
        page.getByRole("button", { name: /e2e-admin@unicloud\.africa/i }),
      ).toBeVisible();
    });
  }
});
